# Generated by Django 5.2.8 on 2025-11-18 09:10

import django.db.models.deletion
from django.db import migrations, models


def populate_product_names(apps, schema_editor):
    """
    Data migration: Copy product names to the new product_name field
    for existing inventory logs before changing CASCADE to SET_NULL.
    This preserves the product names in the audit trail.
    """
    InventoryLog = apps.get_model('api', 'InventoryLog')
    for log in InventoryLog.objects.all():
        if log.product:
            log.product_name = log.product.name
            log.save(update_fields=['product_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_stock_quantity_non_negative'),
    ]

    operations = [
        # Step 1: Add product_name field with default
        migrations.AddField(
            model_name='inventorylog',
            name='product_name',
            field=models.CharField(default='Unknown Product', max_length=200),
        ),
        # Step 2: Populate product_name from existing product FK
        migrations.RunPython(populate_product_names, reverse_code=migrations.RunPython.noop),
        # Step 3: Change FK from CASCADE to SET_NULL (preserves logs after product deletion)
        migrations.AlterField(
            model_name='inventorylog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='api.product'),
        ),
    ]
